spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:com/github/mybatisplusplus/*/dao/xml/*Mapper.xml

debug: true


